# this is just for plot_single_waveform since cmake is too hard


plot_single_wfs: plot_single_wfs.cc
	c++ -o $@ -g  $^ -I../inc/ `root-config --cflags` `root-config --ldflags` `root-config --libs` -L../build/ -lpueorawdata

