#ifndef _PUEO_SENSOR_IDS_COMPAT_H
#define _PUEO_SENSOR_IDS_COMPAT_H


#define PUEO_SENSORS_0x2025(SENSOR)                     \
SENSOR(W1Temps,  ChargeContrHeatsink,       'F','C')     \
SENSOR(W1Temps,  PowerBoxBaseplate,         'F','C')     \
SENSOR(W1Temps,  24VVicor,                  'F','C')     \
SENSOR(W1Temps,  5VVicor,                   'F','C')     \
SENSOR(W1Temps,  4VVicor,                   'F','C')     \
SENSOR(W1Temps,  12V_AFlex,                 'F','C')     \
SENSOR(W1Temps,  12V_BFlex,                 'F','C')     \
SENSOR(W1Temps,  12V_CFlex,                 'F','C')     \
SENSOR(W1Temps,  StatRadPlateInt,           'F','C')     \
SENSOR(W1Temps,  SideofOutboardFPB,         'F','C')     \
SENSOR(W1Temps,  FrontofNavEncl,            'F','C')     \
SENSOR(W1Temps,  FrontofHDAQCrate,          'F','C')     \
SENSOR(W1Temps,  FrontofSciStack,           'F','C')     \
SENSOR(W1Temps,  DynRadPlateInt,            'F','C')     \
SENSOR(W1Temps,  TopofPowerFPB,             'F','C')     \
SENSOR(W1Temps,  FrontofCPUCrate,           'F','C')     \
SENSOR(W1Temps,  FrontofVDAQCrate,          'F','C')     \
SENSOR(W1Temps,  TopofPowerBox,             'F','C')     \
SENSOR(W1Temps,  PVActuator1,               'F','C')     \
SENSOR(W1Temps,  PVActuator2,               'F','C')     \
SENSOR(W1Temps,  LFActuator1,               'F','C')     \
SENSOR(W1Temps,  LFActuator2,               'F','C')     \
SENSOR(W1Temps,  StatRadPlateExt,           'F','C')     \
SENSOR(W1Temps,  DynRadPlateExt,            'F','C')     \
SENSOR(W1Temps,  MIELidExt,                 'F','C')     \
SENSOR(W1Temps,  BatteryBox1Face,           'F','C')     \
SENSOR(W1Temps,  BatteryBox2Face,           'F','C')     \
SENSOR(W1Temps,  SunSensorPhiSect7,         'F','C')     \
SENSOR(W1Temps,  SunSensorPhiSect19,        'F','C')     \
SENSOR(W1Temps,  LFOutwardofBoard4,         'F','C')     \
SENSOR(W1Temps,  LFInwardofBoard6,          'F','C')     \
SENSOR(W1Temps,  LFInwardofBoard3,          'F','C')     \
SENSOR(W1Temps,  LFPowerBoard,              'F','C')     \
SENSOR(W1Temps,  LFOutwardofBoard7,         'F','C')     \
SENSOR(W1Temps,  LFInwardofBoard8,          'F','C')     \
SENSOR(W1Temps,  LFOutwardofBoard1,         'F','C')     \
SENSOR(W1Temps,  AMPA_186,                  'F','C')     \
SENSOR(W1Temps,  AMPA_223,                  'F','C')     \
SENSOR(W1Temps,  AMPA_011,                  'F','C')     \
SENSOR(W1Temps,  AMPA_073,                  'F','C')     \
SENSOR(W1Temps,  AMPA_181,                  'F','C')     \
SENSOR(W1Temps,  AMPA_028,                  'F','C')     \
SENSOR(W1Temps,  AMPA_064,                  'F','C')     \
SENSOR(W1Temps,  AMPA_179,                  'F','C')     \
SENSOR(W1Temps,  UpperIMU,                  'F','C')     \
SENSOR(W1Temps,  StarlinkDishyMount,        'F','C')     \
SENSOR(W1Temps,  StarlinkPowerBox,          'F','C')     \
SENSOR(W1Temps,  ToqueCorner,               'F','C')     \
SENSOR(W1Temps,  AutoBelay,                 'F','C')     \
SENSOR(W1Temps,  AMPA_040,                  'F','C')     \
SENSOR(W1Temps,  AMPA_021,                  'F','C')     \
SENSOR(W1Temps,  AMPA_007,                  'F','C')     \
SENSOR(W1Temps,  AMPA_105,                  'F','C')     \
SENSOR(W1Temps,  AMPA_075,                  'F','C')     \
SENSOR(W1Temps,  AMPA_163,                  'F','C')     \
SENSOR(W1Temps,  AMPA_132,                  'F','C')     \
SENSOR(W1Temps,  AMPA_034,                  'F','C')     \
SENSOR(W1Temps,  AMPA_152,                  'F','C')     \
SENSOR(W1Temps,  AMPA_145,                  'F','C')     \
SENSOR(W1Temps,  AMPA_112,                  'F','C')     \
SENSOR(W1Temps,  AMPA_200,                  'F','C')     \
SENSOR(W1Temps,  AMPA_169,                  'F','C')     \
SENSOR(W1Temps,  AMPA_085,                  'F','C')     \
SENSOR(W1Temps,  AMPA_119,                  'F','C')     \
SENSOR(W1Temps,  AMPA_161,                  'F','C')     \
SENSOR(W1Temps,  AMPA_139,                  'F','C')     \
SENSOR(W1Temps,  AMPA_012,                  'F','C')     \
SENSOR(W1Temps,  AMPA_035,                  'F','C')     \
SENSOR(W1Temps,  AMPA_208,                  'F','C')     \
SENSOR(W1Temps,  AMPA_219,                  'F','C')     \
SENSOR(W1Temps,  AMPA_025,                  'F','C')     \
SENSOR(W1Temps,  AMPA_027,                  'F','C')     \
SENSOR(W1Temps,  AMPA_026,                  'F','C')     \
SENSOR(W1Temps,  AMPA_094,                  'F','C')     \
SENSOR(W1Temps,  AMPA_190,                  'F','C')     \
SENSOR(W1Temps,  AMPA_153,                  'F','C')     \
SENSOR(W1Temps,  AMPA_157,                  'F','C')     \
SENSOR(W1Temps,  AMPA_226,                  'F','C')     \
SENSOR(W1Temps,  AMPA_204,                  'F','C')     \
SENSOR(W1Temps,  AMPA_099,                  'F','C')     \
SENSOR(W1Temps,  AMPA_185,                  'F','C')     \
SENSOR(W1Temps,  AMPA_149,                  'F','C')     \
SENSOR(W1Temps,  AMPA_144,                  'F','C')     \
SENSOR(W1Temps,  AMPA_217,                  'F','C')     \
SENSOR(W1Temps,  AMPA_108,                  'F','C')     \
SENSOR(W1Temps,  PV1PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV5PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV4PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV3PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV7PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV2PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV6PhiSect,                'F','C')     \
SENSOR(W1Temps,  PV8PhiSect,                'F','C')     \
SENSOR(CPU,      Core10,                    'F','C')     \
SENSOR(CPU,      Core2,                     'F','C')     \
SENSOR(CPU,      Core9,                     'F','C')     \
SENSOR(CPU,      Core13,                    'F','C')     \
SENSOR(CPU,      Core12,                    'F','C')     \
SENSOR(CPU,      Core4,                     'F','C')     \
SENSOR(CPU,      Core5,                     'F','C')     \
SENSOR(CPU,      Core11,                    'F','C')     \
SENSOR(CPU,      Core1,                     'F','C')     \
SENSOR(CPU,      Core8,                     'F','C')     \
SENSOR(CPU,      Core3,                     'F','C')     \
SENSOR(CPU,      Core0,                     'F','C')     \
SENSOR(CPU,      Package0,                  'F','C')     \
SENSOR(CPU,      Ambient,                   'F','C')     \
SENSOR(CPU,      PCH,                       'F','C')     \
SENSOR(CPU,      LeftRail,                  'F','C')     \
SENSOR(CPU,      RightRail,                 'F','C')     \
SENSOR(CPU,      GPU,                       'F','C')     \
SENSOR(Mag,      B0,                        'F','G')     \
SENSOR(Mag,      B1,                        'F','G')     \
SENSOR(Mag,      B2,                        'F','G')     \
SENSOR(CC,       OutputPower,               'F','W')     \
SENSOR(CC,       InputPower,                'F','W')     \
SENSOR(CC,       MaxLastSweepPower,         'F','W')     \
SENSOR(CC,       PV,                        'F','V')     \
SENSOR(CC,       VmpLastSweep,              'F','V')     \
SENSOR(CC,       VocLastSweep,              'F','V')     \
SENSOR(CC,       FilteredBattVoltage,       'F','V')     \
SENSOR(CC,       BatteryMin,                'F','V')     \
SENSOR(CC,       BatteryMax,                'F','V')     \
SENSOR(CC,       HoursOn,                   'F','V')     \
SENSOR(CC,       FaultBits,                 'U','X')     \
SENSOR(CC,       ChargingCurrent,           'F','A')     \
SENSOR(CC,       TLocal,                    'F','C')     \
SENSOR(CC,       TRemote,                   'F','C')     \
SENSOR(HK,       24V,                       'F','V')     \
SENSOR(HK,       BATTERY,                   'F','V')     \
SENSOR(HK,       PV,                        'F','V')     \
SENSOR(HK,       12V_C_V,                   'F','V')     \
SENSOR(HK,       RF_OFF_INV,                'F','V')     \
SENSOR(HK,       12V_B_V,                   'F','V')     \
SENSOR(HK,       12V_A_V,                   'F','V')     \
SENSOR(HK,       12V_rail,                  'F','V')     \
SENSOR(HK,       3_3V_rail,                 'F','V')     \
SENSOR(HK,       12V_D_V,                   'F','V')     \
SENSOR(HK,       12V_C_I,                   'F','A')     \
SENSOR(HK,       12V_B_I,                   'F','A')     \
SENSOR(HK,       12V_A_I,                   'F','A')     \
SENSOR(HK,       5V_Vicor_V,                'F','V')     \
SENSOR(HK,       5V_Vicor_I,                'F','A')     \
SENSOR(HK,       4V_Vicor_V,                'F','V')     \
SENSOR(HK,       4V_Vicor_I,                'F','A')     \
SENSOR(RF,       RB1,                       'F','C')     \
SENSOR(RF,       RB2,                       'F','C')     \
SENSOR(RF,       RB3,                       'F','C')     \
SENSOR(RF,       RB4,                       'F','C')     \
SENSOR(RF,       RB5,                       'F','C')     \
SENSOR(RF,       RB6,                       'F','C')     \
SENSOR(DAQ,      V_TURF,                    'F','V')     \
SENSOR(DAQ,      I_TURF,                    'F','A')     \
SENSOR(DAQ,      T_RPU_TURF,                'F','C')     \
SENSOR(DAQ,      T_APU_TURF,                'F','C')     \
SENSOR(DAQ,      T_TURFIO_HL,               'F','C')     \
SENSOR(DAQ,      T_TURFIO_HR,               'F','C')     \
SENSOR(DAQ,      T_TURFIO_VL,               'F','C')     \
SENSOR(DAQ,      T_TURFIO_VR,               'F','C')     \
SENSOR(DAQ,      T_HS_SURF1_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF2_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF3_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF4_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF5_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF6_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF7_HL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF1_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF2_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF3_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF4_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF5_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF6_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF7_HR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF1_VL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF2_VL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF3_VL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF4_VL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF5_VL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF6_VL,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF1_VR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF2_VR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF3_VR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF4_VR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF5_VR,             'F','C')     \
SENSOR(DAQ,      T_HS_SURF6_VR,             'F','C')     \
SENSOR(DAQ,      T_RPU_SURF1_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF2_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF3_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF4_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF5_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF6_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF7_HL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF1_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF2_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF3_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF4_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF5_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF6_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF7_HR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF1_VL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF2_VL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF3_VL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF4_VL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF5_VL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF6_VL,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF1_VR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF2_VR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF3_VR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF4_VR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF5_VR,            'F','C')     \
SENSOR(DAQ,      T_RPU_SURF6_VR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF1_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF2_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF3_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF4_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF5_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF6_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF7_HL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF1_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF2_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF3_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF4_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF5_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF6_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF7_HR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF1_VL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF2_VL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF3_VL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF4_VL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF5_VL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF6_VL,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF1_VR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF2_VR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF3_VR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF4_VR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF5_VR,            'F','C')     \
SENSOR(DAQ,      T_APU_SURF6_VR,            'F','C') 


#define PUEO_SENSOR_ENUM_DEF_0x2025(SUBSYS,NAME,TYPETAG,KIND) PUEO_SENSOR_##SUBSYS##_##NAME##_0x2025,
enum e_pueo_sensors_0x2025
{
 PUEO_SENSORS_0x2025(PUEO_SENSOR_ENUM_DEF_0x2025)
};



#endif
